### ISSUE TITLE
Handling restart

### ISSUE THREAD

**Issue by athoune** [factorysh/density#17]
With bbolt persistance, we can reboot `batch-scheduler` without stopping any containers, and even upgrade the service.

* [ ] id of main service is persisted
* [ ] set Task status as Docker say (status + return code)

**Comment by papey** [comment]
- Add id leader container in bbolt storage
- Add Load func to Scheduler
   - Get all tasks from bbolt
   - Check container id state for each tasks
   - Return code of leader container is used to decided what to do

**Comment by papey** [comment]
Closed by #22
